name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        python:
          - '3.13'
        platform:
          - ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        pip install --user pipenv
        pipenv sync

    - name: Build documentation
      run: |
        pipenv run make html

    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
        path: build/html

    - name: Deploy files
      uses: peaceiris/actions-gh-pages@v4
      with:
        force_orphan: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/html
        user_email: 'github-actions[bot]@users.noreply.github.com'
        user_name: 'github-actions[bot]'
