name: Sphinx build

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3.12'

    - name: Install Pipenv and requirements, and build docs
      run: |
        pip install --user pipenv
        pipenv install
        pipenv run make html

    - name: Deploy HTML
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/html
