name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "./"
    - name: Commit documentation changes
      run: |
        ls -R build/html
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
      with:
        name: html-docs
        path: build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/html
